;set to true to roll back to old score_weighted ordering for guides
DISABLE_VOTE_DECAY=0

;Disabled Auto-Promotion
DISABLE_AUTOMATIC_PROMOTIONS=1

;how many web nodes this site has - used in online user counts
WEB_NODE_COUNT=4

;DEPRECATED: used for selecting what emblem to show for each elo
BRONZE_ELO_RATING=0
SILVER_ELO_RATING=1150
GOLD_ELO_RATING=1500
PLATINUM_ELO_RATING=1850
DIAMOND_ELO_RATING=2200

;Used for TFT sets, add new ones to the Patch class!
TFT_SET_2_CUTOFF=2019-11-20 00:00:00
TFT_SET_3_CUTOFF=2020-03-18 00:00:00
TFT_SET_4_CUTOFF=2020-09-16 00:00:00
TFT_SET_5_CUTOFF=2021-04-28 00:00:00
TFT_SET_6_CUTOFF=2021-11-01 00:00:00
TFT_SET_7_CUTOFF=2022-06-07 00:00:00
TFT_SET_8_CUTOFF=2022-12-06 00:00:00
TFT_SET_9_CUTOFF=2023-06-09 00:00:00
TFT_SET_10_CUTOFF=2023-11-17 00:00:00
TFT_SET_11_CUTOFF=2024-03-13 00:00:00
TFT_SET_12_CUTOFF=2024-07-26 00:00:00
TFT_SET_13_CUTOFF=2024-11-14 00:00:00

;Used for TFT revival sets, add new ones to the Patch class!
REVIVAL_SET_3_5_CUTOFF=2023-11-17 00:00:00
REVIVAL_SET_5_5_CUTOFF=2024-09-20 00:00:00
REVIVAL_SET_4_5_CUTOFF=2025-01-23 00:00:00

;Used for marking guides with a new season when updated.
CURRENT_TFT_SET=13
CURRENT_TFT_TITLE=Into the Arcane
CURRENT_REVIVAL_SET=4.5
CURRENT_REVIVAL_TITLE=Festival of Beasts
REVIVAL_ACTIVE=true

;forum topic ids used for automatic promotion/nomination threads
EDITOR_FORUM_TOPIC_ID=25
SCOUT_FORUM_TOPIC_ID=26
VETERAN_FORUM_TOPIC_ID=9

;forum thread links used in automatic promotion/nomination pms/emails
EDITORS_HANDBOOK_URL=/league-of-legends/forum/editors-office/editors-handbook-10745
SCOUTS_HANDBOOK_URL=/league-of-legends/forum/scouts-guild/scouts-handbook-10746
VETERANS_HANDBOOK_URL=/league-of-legends/forum/veterans-hall/veterans-handbook-10747

;this is a special date where a change was made to the platform's voting. tbh i forget now what that change was :) will have to look through the code to find if/where/how this is used
VOTE_LOCK_CUTOFF_DATE=2010-08-01 00:00:00

;various forms of the game and site name that are used throughout the platform and template, which will be different on every site
GAME_DISPLAY_NAME=League of Legends
GAME_ACRONYM=LoL
SITE_DISPLAY_NAME=MOBAFire
LOGGING_FILE_PREPEND=mobafire-
SITE_CLASS_PREFIX=Lol_
NETWORK_DISPLAY_NAME=MOBAFire Network
BASE_URL_STRING=league-of-legends
BLOG_ON_TOPIC_CATEGORY=leagueoflegends
GAME_USES_STEAM=false
DOMAIN_NAME=mobafire.com
GAME=league
GENRE=moba
COMPANY=riot

;different sites have different names for their characters (champion/hero/god), these are used to make code portable
HERO_DISPLAY_NAME=Champion
HERO_DISPLAY_NAME_PLURAL=Champions
HERO_URL_STRING=champion
HERO_URL_STRING_PLURAL=champions
HERO_RELATION_TYPE=Champion

;all sites call guides "guides" except mobafire - it still calls guides "builds" - this is required for backwards compatibility
BUILD_OR_GUIDE=build
GUIDE_TOP_RATED_SORT_COLUMN=score_final
GUIDE_SCORE_DISPLAY_COLUMN=score_final
GUIDE_BAR_DISPLAY_COLUMN=score_final
GUIDE_SCORE_DISPLAY_MULTIPLIER=100
GUIDE_VOTE_COUNT_DISPLAY_COLUMN=vote_count_final
GUIDE_BAR_MAX_PERCENT=90
GUIDE_VOTE_DECAY_MINIMUM_VOTES=30
GUIDE_VOTE_DECAY_MAXIMUM_VOTES=60
NEW_GUIDE_SCORE_THRESHOLD=5
NEW_GUIDE_DAYS_THRESHOLD=14

TIER_LIST_BAR_DISPLAY_COLUMN=score_decayed
TIER_LIST_BAR_DISPLAY_COLUMN_GUEST=score_decayed_guest
TIER_LIST_BAR_MAX_PERCENT=90

TEAM_LIST_BAR_DISPLAY_COLUMN=score_decayed
TEAM_LIST_BAR_DISPLAY_COLUMN_GUEST=score_decayed_guest
TEAM_LIST_BAR_MAX_PERCENT=90

;sets the minimum number of up scouts a guide needs to receive the scout badge
MINIMUM_SCOUT_SCORE=2

;this sets a minimum description length (in characters, NOT WORDS, including bbcode) required before guides can be considered "complete". guides with text shorter than this limit will be filtered out of many lists on the site by default.
MINIMUM_BUILD_DESCRIPTION_LENGTH=3000

;DEPRECATED: temporary checks used during the transition to network accounts - these should be removed once we no longer need them in the code
ENABLE_EMAIL_CHANGE=true
ENABLE_NETWORK_REGISTRATION=true
ENABLE_NETWORK_ACCOUNT_UPDATES=true
ENABLE_NETWORK_NICKNAME_RESERVATION=true
;ENABLE_NETWORK_LOG_IN=false
;ENABLE_REGISTRATION_ON_NETWORK_LOG_IN=false

;enable embedded twitch stream
TWITCH_STREAM_ENABLED=true
TWITCH_STREAM_RATE_PERCENT=100
TWITCH_STREAM_CHANNEL=mobafire

;Stripe
STRIPE_TEST=0
PAYPAL_TEST=0

TWITTER_LINK=https://twitter.com/mobafire
FACEBOOK_LINK=https://www.facebook.com/MOBAFire
DISCORD_LINK=https://discord.gg/KxXZ8P8Tmt

;Name of current Community Manager
COMMUNITY_MANAGER=Hades4u

;Twitch Game
TWITCH_GAME=League of Legends
TWITCH_GAME_2=Teamfight Tactics

ENABLE_SOCIAL_LOGIN=1

ALLOW_GUEST_VOTING_BUILD=1
ALLOW_GUEST_VOTING_TIER_LIST=1
ALLOW_GUEST_VOTING_TEAM_LIST=1

;enable lazyloading of images
ENABLE_IMAGE_LAZYLOAD=1

SHOW_DEV_ADS=0

;network sites
SITE_NAMES=[Mobafire, League of graphs, Porofessor, Valofessor]
SITE_URLS=[https://mobafire.com, https://leagueofgraphs.gg, https://porofessor.gg, https://valofessor.gg]
